name: Go CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.22.x, 1.21.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: |
          export GO111MODULE="on"
          export GOPATH=""
          cd go
          go test -v ./...
        shell: bash
