name: JavaScript CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: node js/test_money.js
        shell: bash
